os:
  - linux
language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter build apk
